---
- name: Ensure python-pip is installed
  apt:
    name: "{{ dehydrated_pip_package }}"
  when: dehydrated_install_pip

- name: Ensure virtualenv is installed
  pip:
    name: virtualenv
    executable: "{{ dehydrated_pip_executable|default(omit) }}"

- name: Install dns-lexicon
  pip:
    name: dns-lexicon
    executable: "{{ dehydrated_pip_executable|default(omit) }}"
    virtualenv: "{{ dehydrated_lexicon_venv }}"

- name: Link lexicon executables to /usr/local/bin
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
  with_items:
    - { src: "{{ dehydrated_lexicon_venv }}/bin/chardetect", dest: "{{ lexicon_path }}/chardetect" }
    - { src: "{{ dehydrated_lexicon_venv }}/bin/futurize", dest: "{{ lexicon_path }}/futurize" }
    - { src: "{{ dehydrated_lexicon_venv }}/bin/lexicon", dest: "{{ lexicon_path }}/lexicon" }
    - { src: "{{ dehydrated_lexicon_venv }}/bin/pasteurize", dest: "{{ lexicon_path }}/pasteurize " }
    - { src: "{{ dehydrated_lexicon_venv }}/bin/tldextract", dest: "{{ lexicon_path }}/tldextract" }
  vars:
    lexicon_path: '/usr/local/bin'

- name: Copy hook script
  copy:
    dest: /etc/dehydrated/hooks.d/01lexicon
    src: 01lexicon
    owner: root
    group: root
    mode: "0700"
