---

# This handler needs to be defined before "run dehydrated",
# as handlers run in the order __defined__, not _called__.
- name: update account details
  command: "{{ dehydrated_install_root }}/dehydrated --account"

- name: run dehydrated
  command: "{{ dehydrated_renew_command }}"
  when: dehydrated_run_on_changes

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Remove timer
  systemd:
    name: dehydrated.timer
    enabled: no
    state: stopped
